openapi: 3.0.1
info:
  title: OpenDSU communication APIs
  description: This a project to model OpenDSU communication systems using OpenAPI
    standard
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: 1.0.0
servers:
  - url: http://localhost:8080
  - url: https://csc.rms.pharmaledger.app
tags:
  - name: APIHub APIs - Anchoring
    description: Service that facilitate the anchoring process
    externalDocs:
      description: Find out more
      url: https://opendsu.com

paths:

  /anchor/{domain}/create-anchor/{keySSI}:
    put:
      tags:
        - APIHub APIs - Anchoring
      summary: Publish creation of a new anchor
      operationId: create-anchor
      parameters:
        - name: domain
          in: path
          required: true
          description: The domain should be the same with the domain from the AnchorId
          schema:
            type: string
        - name: keySSI
          in: path
          description: keySSI base58
          required: true
          style: simple
          explode: false
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/body'
      responses:
        "201":
          description: Succesufuly created a new anchor for AnchorId
        "409":
          description: Access Error
        "403":
          description: Access to resource is forbidden
        "429":
          description: Too Many Requests
        "500":
          description: Fallback generic error response
  /anchor/{domain}/append-to-anchor/{keySSI}:
    put:
      tags:
        - APIHub APIs - Anchoring
      summary: Append a new hashlink to an AnchorId
      operationId: append-anchor
      parameters:
        - name: domain
          in: path
          required: true
          description: The domain should be the same with the domain from the AnchorId
          schema:
            type: string
        - name: keySSI
          in: path
          description: keySSI base58
          required: true
          style: simple
          explode: false
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/body'
      responses:
        "201":
          description: Succesufuly appended the hashlink for AnchorId
        "409":
          description: Access Error
        "403":
          description: Access to resource is forbidden
        "428":
          description: Hashlink for AnchorId are out of sync
        "429":
          description: Too Many Requests
        "500":
          description: Fallback generic error response
  /anchor/{domain}/create-or-update-multiple-anchors:
    put:
      tags:
        - APIHub APIs - Anchoring
      summary: Create or update multiple anchors in the same request
      operationId: createOrUpdateMultipleAnchors
      parameters:
        - name: domain
          in: path
          required: true
          description: All the created or updated anchors should be from the same domain
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/body'
      responses:
        "201":
          description: Succesufuly created or updated the provided anchors
        "403":
          description: Access to resource is forbidden
        "409":
          description: Access Error
        "428":
          description: At least one Hashlink for one AnchorId is out of sync
        "429":
          description: Too Many Requests
        "500":
          description: Fallback generic error response
  /anchor/{domain}/get-all-versions/{keySSI}:
    get:
      tags:
        - APIHub APIs - Anchoring
      summary: Get all the versions of an anchor
      operationId: getAllVersions
      parameters:
        - name: domain
          in: path
          required: true
          description: The domain should be the same with the domain from the AnchorId
          schema:
            type: string
        - name: keySSI
          in: path
          description: keySSI base58
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        "200":
          description: Returns the list of the versions of a keySSI
        "404":
          description: Invalid AnchorId
        "429":
          description: Too Many Requests
components:
  schemas:
    body:
      type: object
      properties:
        hashLinkIds:
          $ref: '#/components/schemas/hashLinkIds'
        digitalProof:
          type: string
        zkp:
          type: string
    hashLinkIds:
      type: object
      properties:
        new:
          type: string
        last:
          type: string
