openapi: 3.0.1
info:
  title: OpenDSU communication APIs
  description: This a project to model OpenDSU communication systems using OpenAPI
    standard
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: 1.0.0
servers:
  - url: http://localhost:8080
  - url: https://csc.rms.pharmaledger.app
tags:
  - name: APIHub APIs - SSO Secrets
    description: Provides SSO Secrets management. All APIs calls should be authorized with a Bearer token.
    externalDocs:
      description: Find out more
      url: https://opendsu.com
security:
  - authorization: []
paths:

  /secrets/getSSOSecret/{appName}:
    get:
      tags:
        - APIHub APIs - SSO Secrets
      summary: Access user SSO secrets for a particular appName
      parameters:
        - name: appName
          in: path
          required: true
          description: The application name for which the secret is requested
          schema:
            type: string
        - name: user-id
          in: header
          schema:
            type: string
      responses:
        "200":
          description: Returns the secret for the specified "user-id" and "appName"
        "404":
          description: A secret for the specified "user-id" and "appName" was not found
        "403":
          description: Unauthorized access
        "500":
          description: Wrong secret format or unathorized access
    put:
      tags:
        - APIHub APIs - SSO Secrets
      summary: Enable and add user SSO secret for a particular appName.
      parameters:
        - name: appName
          in: path
          required: true
          description: The application name for which the secret is enabled and added
          schema:
            type: string
        - name: user-id
          in: header
          schema:
            type: string
      requestBody:
        description: Secret that should be stored
        content:
          application/json:
            schema:
              type: object
      responses:
        "200":
          description: Operation completed successfully
        "403":
          description: Unauthorized access
        "404":
          description: A secret for the specified "user-id" and "appName" was not found
        "500":
          description: Wrong secret format or other internal error

  /deactivateSSOSecret/{appName}/{did}:
    delete:
      tags:
        - APIHub APIs - SSO Secrets
      summary: Deactivate user SSO secret for a particular appName.
      parameters:
        - name: appName
          in: path
          required: true
          description: The application name for which the secret is deactivated
          schema:
            type: string
        - name: did
          required: true
          in: path
          description: The DID of the user encoded in base58
          schema:
            type: string
      responses:
        "200":
          description: Operation completed successfully
        "403":
          description: Unauthorized access
        "404":
          description: A secret for the specified "did" and "appName" was not found

  /removeSSOSecret/{appName}/{did}:
    delete:
      tags:
        - APIHub APIs - SSO Secrets
      summary: Deactivate and remove user SSO secret for a particular appName.
      parameters:
        - name: appName
          in: path
          required: true
          description: The application name for which the secret is deactivated and removed
          schema:
            type: string
        - name: did
          required: true
          in: path
          description: The DID of the user encoded in base58
          schema:
            type: string
      responses:
        "200":
          description: Operation completed successfully
        "403":
          description: Unauthorized access
        "404":
          description: A secret for the specified "did" and "appName" was not found

components:
  securitySchemes:
    authorization:
      type: http
      scheme: bearer
      bearerFormat: JWT
